### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by zaharcelac** [mikebarkmin/baby-tracker#12]
It would be great if all texts/strings are stored in a separate "language" file(s).

**Comment by mikebarkmin** [comment]
I have added lingui. We can now add languages as we like with `yarn locale:add es` for example. Then you extract the locales with `yarn locale:extract` and need to edit the corresponding po file. Afterwards we can compile the po files with `yarn locale:compile` and the new locale is usable.

Currently, the user language is the same as the browser language. I have also added translations for english and german.
