### ISSUE TITLE
Dealing with the data

### ISSUE THREAD

**Issue by mikebarkmin** [mikebarkmin/baby-tracker#19]
- Add the ability to export the data in JSON format.
- Add the ability to delete the data.

**Comment by steini86** [comment]
Hi Mike, thanks for sharing that project!
Whats the best method to extract the data at the moment? I'd like to do some statistics, like a week/month-view where I can see the feeding times, diaper changes, etc. Also I would like to have a backup at some point. Thanks!

**Comment by mikebarkmin** [comment]
I have added a "Backup and Restore" section to the README. This will create a MongoDB archive. This is of course only possible, if you host baby-tracker yourself and have access to the MongoDB. I will also add an export option in the frontend in the coming days. This will be just a JSON file containing all information.
