### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by steini86** [mikebarkmin/baby-tracker#225]
A dark theme wold be nice for feeding at night. For example with a button in the header which changes to a dark background

**Comment by mikebarkmin** [comment]
A pitch black dark mode? #000000 as background color.
Or a more subtile dark mode? Darkgrey as background color.

What do you like more?

**Comment by mikebarkmin** [comment]
See Version 1.8.0 will have a dark mode. The docker image is currently building :) 

Here a preview:

![Dark Mode](https://raw.githubusercontent.com/mikebarkmin/baby-tracker/master/.github/darkmode.png)

**Comment by mikebarkmin** [comment]
Close by 5c5f77b7e5f5bb0a154e5306845252d369fd02e3
