### ISSUE TITLE
Add "how to use" in GitHub README

### ISSUE THREAD

**Issue by bbrewington** [mikebarkmin/baby-tracker#439]
I'm looking to use this, and just learned about it a couple minutes ago.  Not necessarily looking to develop the app or tinker, just would like to set it up and get going.

Maybe add a "how to use" or "quickstart" section to the README?  Or link to whatever website has that info?

**Comment by mikebarkmin** [comment]
You can find the information under Deploy https://github.com/mikebarkmin/baby-tracker#deploy.
