### ISSUE TITLE
TypeError?(pages/EventsPage)

### ISSUE THREAD

**Issue by mikebarkmin** [mikebarkmin/baby-tracker#55]
Cannot read property '_id' of undefined

https://sentry.io/share/issue/ca6d04c646b34cfa84e402a2458a1e3f/

**Comment by shakti97** [comment]
Working on it

**Comment by shakti97** [comment]
![babyCry](https://user-images.githubusercontent.com/30585570/66703217-dbe46380-ed2d-11e9-985d-3a713c1a4166.PNG)
i just tried these commands
Fork https://github.com/mikebarkmin/baby-tracker.git
git clone https://github.com/{yourusername}/baby-tracker.git
cd baby-tracker
docker-compose up

**Comment by mikebarkmin** [comment]
My bad. When the volume is mounted, the node_modules directory which was installed via the docker build will be overwritten. Therefore we need to `yarn install` in the `client`directory, before `docker-compose up`. I will add this to the README. Sorry

**Comment by shakti97** [comment]
Should i do that for you
